#### Investigating the labels class

In [1]:
import os 
import numpy as np
import pandas as pd

In [7]:
df = pd.read_parquet('data/AMLP/DF_2024_11_26.parquet')
df.head()

,Volume,Dividends,open_low,open_close,open_high,high_low,low_close,high_close,gap,AMLP_mom1,...,upsidegap_two_crows,three_black_crows,three_white_soldiers,advance_block,stalled_pattern,counterattack,tasuki,rf_three_methods,separating_lines,labels
Date,,,,,,,,,,,,,,,,,,,,,
2024-11-26,257751,0.0,0.000000,-0.589910,0.834011,0.827113,-0.589910,-0.242082,0.000000,0.59,...,0,0,0,0,0,0,0,0,0,1
2024-11-25,1471400,0.0,1.845166,1.403931,0.080225,1.923848,-0.449530,-1.482966,0.463429,-0.95,...,0,0,0,0,0,0,0,0,0,0
2024-11-22,1896200,0.0,0.182815,-0.812513,0.893764,1.067042,-0.997151,-0.080532,0.203542,1.02,...,0,0,0,0,0,0,0,0,0,1
2024-11-21,1476800,0.0,0.471698,-0.758819,0.902379,1.361789,-1.236349,-0.142276,0.556816,1.32,...,0,0,0,0,0,0,0,0,0,1
2024-11-20,1783300,0.0,0.865979,0.020619,0.268041,1.130989,-0.852745,-0.287888,0.020623,0.00,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df.labels.value_counts()

labels
0    1188
1    1089
Name: count, dtype: int64