In [48]:
import os
import numpy as np 
import pandas as pd 
import joblib

from techinical_analysis import * 
from Preprocessing_functions import *

In [49]:
os.getcwd()

'c:\\Users\\User\\Documents\\ATS_Development\\Strat_1'

In [50]:
ticker = "SPY"

# LOAD DF FOR MODEL BUILDING 
FILE_PATH = f"Data/{ticker}/df/"
print("DataFrames for model building: ", os.listdir(FILE_PATH))
idx = 0 if len(os.listdir(FILE_PATH)) < 3 else int(input("Select file index: "))
DF_NAME = os.listdir(FILE_PATH)[idx] 
FILE_PATH_NAME = FILE_PATH + DF_NAME

df_model = pd.read_parquet(FILE_PATH_NAME)
df_model = format_idx_date(df_model)
df_model.head()

DataFrames for model building:  ['df_SPY_k3_202402012133.parquet', 'Junk']

,labels,open_low,open_close,gap,open_high,low_close,high_close,high_low,Dividends,Volume,...,SPY_mom3,SPY_mom4,SPY_mom5,SPY_mom10,SPY_mom15,SPY_mom20,SPY_mom60,SPY_mom120,SPY_mom180,SPY_mom240
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-15,0,1.363875,1.293933,0.380295,-0.192341,-0.070909,-1.483421,1.553229,0.0,176613900,...,-1.79,-2.56,-3.34,-3.17,-4.20,1.12,5.16,1.69,7.28,16.50
2015-01-16,1,0.112333,-1.436680,-0.124004,-1.531276,-1.550755,-0.093170,1.618820,0.0,211879600,...,-0.23,-0.50,-1.28,-1.85,-2.96,0.47,4.47,2.98,8.67,17.21
2015-01-20,2,1.103176,0.168379,0.384683,-0.156767,-0.945224,-0.324638,1.257971,0.0,130991100,...,0.60,-0.01,-0.29,0.17,-3.06,-1.74,5.44,3.64,9.06,17.61
2015-01-21,1,0.274116,-0.787356,-0.279167,-1.073137,-1.064390,-0.282747,1.332949,0.0,122942700,...,2.04,1.11,0.49,1.64,-2.70,-1.66,4.76,4.15,9.41,16.66
2015-01-22,1,0.812306,-1.036986,0.445576,-1.111879,-1.864436,-0.074070,1.903025,0.0,174356000,...,2.22,3.56,2.61,1.88,-0.72,-0.66,5.50,7.83,12.01,16.95

In [51]:
ticker = "SPY"
n_clusters = 3 
time_period = "360mo" # must be the same as in 1_Data_Acquisition or larger

In [52]:
### LOAD KMEANS MODEL ###
KMEANS_PATH = f"kmeans_models/{ticker}/"
#print(os.getcwd())
KMEANS_MODEL_PATH = os.listdir(KMEANS_PATH)
try:
    KMEANS_MODEL_PATH.remove('Junk')
except ValueError:
    print(' ')    

print(KMEANS_MODEL_PATH)
idx = 0 if len(KMEANS_MODEL_PATH) < 2 else int(input("Select file index: "))
KMEANS_NAME = KMEANS_MODEL_PATH[idx]
print("Chosen K_MEANS MODEL file: ", KMEANS_NAME)
FILE = KMEANS_PATH + KMEANS_NAME
loaded_kmeans = joblib.load(FILE)

### LOAD FEAT LIST TO ORDER THE DATA ###
FEAT_PATH = f"model_features/{ticker}/"
FEAT_FILES = os.listdir(FEAT_PATH)
try:
    FEAT_FILES.remove('Junk')
except ValueError:
    print(' ')
print(FEAT_FILES)
idx = 0 if len(FEAT_FILES) < 2 else int(input("Select file index (e.g. 0,1,2)"))
FEAT_NAME = FEAT_FILES[idx]
MODEL_FEAT = pd.read_csv(FEAT_PATH + FEAT_NAME)['0'].to_list()
#MODEL_FEAT.pop(-1)

# Cluster stats
STATS_PATH = f"Data/{ticker}/k_stats/"
STATS_FILES = os.listdir(STATS_PATH)
try:
    STATS_FILES.remove('Junk')
except ValueError:
    print(' ')
print("KMEANS Stats files: ", STATS_FILES)
idx = 0 if len(STATS_FILES) < 2 else int(input("Select file index: "))
STATS_NAME = STATS_FILES[idx]
print("Chosen K_STATS file: ", STATS_NAME)
cluster_stats = pd.read_csv(STATS_PATH + STATS_NAME).set_index("Unnamed: 0")

# LOAD DF FOR MODEL BUILDING TO CHECK DATE RANGES 
DF_PATH = f"Data/{ticker}/df/"
DF_FILES = os.listdir(DF_PATH)
try:
    DF_FILES.remove('Junk')
except ValueError:
    print(' ')
print("DataFrames for model building: ", DF_FILES)
idx = 0 if len(DF_FILES) < 2 else int(input("Select file index: "))
DF_NAME = DF_FILES[idx] 
print("Chosen DataFrame file: ", DF_NAME)
df_dates = pd.read_parquet(DF_PATH + DF_NAME)
df_dates = format_idx_date(df_dates)


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

['kmeans_model_df_SPY_k3_202402012133.joblib']
Chosen K_MEANS MODEL file:  kmeans_model_df_SPY_k3_202402012133.joblib
['LSTM_df_SPY_k3_202402012133_NFEAT23.csv']
KMEANS Stats files:  ['KMEANS_Stats_df_SPY_k3_202402012133.csv']
Chosen K_STATS file:  KMEANS_Stats_df_SPY_k3_202402012133.csv
DataFrames for model building:  ['df_SPY_k3_202402012133.parquet']
Chosen DataFrame file:  df_SPY_k3_202402012133.parquet

c:\Users\User\.conda\envs\pytorch\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator KMeans from version 1.2.2 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [53]:
### DOWNLOAD DATA ###
df = downlaod_symbol_data(ticker, period = time_period)
# Use an alternative to yfinance
#df = download_data(ticker, days = 7200)
df = format_idx_date(df)
print('Start date: ',df.index.min())
df.head()

Start date:  1995-04-24 00:00:00

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains,open_low,open_close,open_high,high_low,low_close,high_close,gap
Date,,,,,,,,,,,,,,,
1995-04-24,29.95,30.32,29.95,30.32,169000,0.0,0.0,0.0,0.000000,-1.235392,-1.235392,1.220317,-1.235392,0.000000,NaN
1995-04-25,30.27,30.32,30.22,30.24,293200,0.0,0.0,0.0,0.165180,0.099108,-0.165180,0.329815,-0.066181,-0.263852,-0.164908
1995-04-26,30.18,30.28,30.11,30.26,204400,0.0,0.0,0.0,0.231942,-0.265076,-0.331345,0.561427,-0.498173,-0.066050,-0.198413
1995-04-27,30.22,30.36,30.20,30.34,502200,0.0,0.0,0.0,0.066181,-0.397088,-0.463269,0.527009,-0.463576,-0.065876,-0.132188
1995-04-28,30.33,30.43,30.14,30.38,130800,0.0,0.0,0.0,0.626442,-0.164853,-0.329707,0.953007,-0.796284,-0.164312,-0.032960

In [54]:
# REMOVE DATA SNOOPING 
out_sample = True
manual = True

if out_sample is True:
    
    if manual != True:
        start_date = df_dates.index.min()
        df = df[df.index <= start_date]
    
    else: 
        #Manually choosing the cutoff date
        df = df[df.index >= '2022-07-01']
        #df = df[df.index >= '2010-01-01']
    
    del DF_NAME, df_dates

In [55]:
df = create_momentum_feat(df, ticker).dropna()
df = momentum_oscillators(df)
df = volatility(df)
df = reversal_patterns(df) 
df = continuation_patterns(df)
df = magic_doji(df)
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'Capital Gains', 'open_low', 'open_close', 'open_high', 'high_low',
       'low_close', 'high_close', 'gap', 'SPY_mom1', 'SPY_mom2', 'SPY_mom3',
       'SPY_mom4', 'SPY_mom5', 'SPY_mom10', 'SPY_mom15', 'SPY_mom20',
       'SPY_mom60', 'SPY_mom120', 'SPY_mom180', 'SPY_mom240', 'rsi',
       'macd_values', 'macd_signal_line', 'atr', 'bband_up', 'bband_mid',
       'bband_low', 'hammer', 'hanging_man', 'engulfing_pattern', 'dark_cloud',
       'piercing_line', 'morning_star', 'evening_star', 'shooting_star',
       'inverted_hammer', 'harami', 'harami_cross', 'belt_hold',
       'upsidegap_two_crows', 'three_black_crows', 'three_white_soldiers',
       'advance_block', 'stalled_pattern', 'counterattack', 'tasuki',
       'rf_three_methods', 'separating_lines', 'long_legged_doji',
       'gravestone_doji', 'dragonfly_doji', 'tristar_doji'],
      dtype='object')

In [56]:
### ASSIGN CLUSTER TO OBSERVATION ###
data = df[["open_low", "open_close", "gap"]].dropna()
print(data.shape)
k_predictions = pd.DataFrame(loaded_kmeans.predict(data), columns = ["labels"], index = data.index)
#data = data.merge(k_predictions, left_index = True, right_index = True)#.reset_index()
del FILE, KMEANS_PATH, loaded_kmeans

df_model = df.merge(k_predictions, left_index = True, right_index = True)
df_model.head()

(465, 3)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains,open_low,open_close,...,stalled_pattern,counterattack,tasuki,rf_three_methods,separating_lines,long_legged_doji,gravestone_doji,dragonfly_doji,tristar_doji,labels
Date,,,,,,,,,,,,,,,,,,,,,
2023-06-15,424.70,432.06,424.60,430.80,110303100,0.00,0.0,0.0,0.023546,-1.436308,...,0,0,0,0,0,0,0,0,0,1
2023-06-16,432.81,433.39,428.85,429.33,114121300,1.64,0.0,0.0,0.914951,0.804048,...,0,0,0,0,0,0,0,0,0,2
2023-06-20,427.37,428.27,425.00,427.10,76160400,0.00,0.0,0.0,0.554555,0.063177,...,0,0,0,0,0,0,0,0,0,2
2023-06-21,426.11,426.92,424.32,424.92,76982300,0.00,0.0,0.0,0.420079,0.279271,...,0,0,0,0,0,0,0,0,0,2
2023-06-22,423.95,426.56,423.61,426.45,70637200,0.00,0.0,0.0,0.080198,-0.589692,...,0,0,0,0,0,0,0,0,0,1

In [57]:
# To load the model later:
model = joblib.load("rf_models/rf_NFEAT22_2025_04_22.pkl")

In [58]:
##### RENAME MODEL FEATURES WHERE TICKERS DO NOT COINCIDE FOR TESTING SPY MODEL ON OTHERS 
MODEL_FEAT = [i.replace('SPY', ticker) for i in MODEL_FEAT]

len(MODEL_FEAT)

23

In [68]:
predictions = model.predict(df_model[MODEL_FEAT[1:-1]])
predictions = pd.DataFrame(predictions, index = df_model.index)
predictions.columns = ['predictions']
predictions

            predictions
Date
2023-06-15          0.0
2023-06-16          1.0
2023-06-20          1.0
2023-06-21          0.0
2023-06-22          0.0
...                 ...
2025-04-16          0.0
2025-04-17          0.0
2025-04-21          0.0
2025-04-22          0.0
2025-04-23          0.0

[465 rows x 1 columns]

In [69]:
df_model = df_model.merge(predictions, left_index = True, right_index = True)

In [70]:
### CALCULATE MODEL ACCURACY 
df_acc = df_model[['labels', 'prediction']].dropna()
#df_acc.predictions = df_acc.predictions.replace(0,2)
#df_acc.labels = df_acc.labels.replace(0,2)
df_acc['true_false_prediction'] = (df_acc['labels'] == df_acc['prediction'])
print('Accuracy: %', round(df_acc['true_false_prediction'].sum() / df_acc.shape[0], 4)*100)

Accuracy: % 20.0

In [71]:
df2 = df_model.copy()
df2.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains,open_low,open_close,...,tasuki,rf_three_methods,separating_lines,long_legged_doji,gravestone_doji,dragonfly_doji,tristar_doji,labels,prediction,predictions
Date,,,,,,,,,,,,,,,,,,,,,
2023-06-15,424.70,432.06,424.60,430.80,110303100,0.00,0.0,0.0,0.023546,-1.436308,...,0,0,0,0,0,0,0,1,0.0,0.0
2023-06-16,432.81,433.39,428.85,429.33,114121300,1.64,0.0,0.0,0.914951,0.804048,...,0,0,0,0,0,0,0,2,1.0,1.0
2023-06-20,427.37,428.27,425.00,427.10,76160400,0.00,0.0,0.0,0.554555,0.063177,...,0,0,0,0,0,0,0,2,1.0,1.0
2023-06-21,426.11,426.92,424.32,424.92,76982300,0.00,0.0,0.0,0.420079,0.279271,...,0,0,0,0,0,0,0,2,0.0,0.0
2023-06-22,423.95,426.56,423.61,426.45,70637200,0.00,0.0,0.0,0.080198,-0.589692,...,0,0,0,0,0,0,0,1,0.0,0.0

In [72]:
# =============================================================================
# #### BACKTESTING ####
# =============================================================================
#tc = 3

#create a list of clusters to use in the backtesting df1
k_names = []

for n in range(0,3):
    
    open_low = cluster_stats[f'open_low_{n}']['median']
    open_close = cluster_stats[f'open_close_{n}']['median']
    
    if open_low and open_close >= 0:
        k_names.append(n)
        
    if open_low > open_close and open_low > 0 and abs(open_close)*3 < open_low:
        if n not in k_names:
            k_names.append(n)

In [73]:
### CHOOSE A START DATE FROM THE RETURNS FILES 
from dateutil.relativedelta import relativedelta
start_date_returns = '2006-01-01' # choose here
df2 = df2[df2.index >= start_date_returns]
df_start_date = df2.index.min()

# historic returns for this strategy 
#print('End date: ', end_date)
print('Start date: ', df_start_date)

Start date:  2023-06-15 00:00:00

In [74]:
### INIATIALIZE PARAMETERS - kelly, capital, trade clusters etc ###

start_capital = 1e4
no_trade_k = [i for i in range(0,3) if i not in k_names][0]
df = pd.DataFrame()
tc = 0.003
half_kelly_metric = False

if half_kelly_metric is True:
    
    hk_date = (df_start_date + relativedelta(months= 6)).strftime('%Y-%m-%d')
    print('HK Start date: ', hk_date)
    df2 = df2[df2.index >= hk_date]
    
    try:
        half_kelly = kelly_criterion(ticker, date_to=hk_date, path = 'strat_returns/Testing/no_kelly_criterion_returns') / 2 
    except FileNotFoundError:
        half_kelly = 1
        print('NO Half Kelly Available')
else: 
    half_kelly = 1

In [75]:

for date, row in df2.iterrows():
    #break
    if half_kelly_metric is True:
        try:
            half_kelly = kelly_criterion(ticker, date, path = returns_path) / 2
        except FileNotFoundError:
            half_kelly =  1
            print(date)
    
    else: 
        half_kelly = 1 
        print('No kelly critetion: ', date)
        
        
    for k in range(len(k_names)):
        
        #row['bp_used'] = (start_capital * half_kelly, 2) # needs more work to fix dataypes error (passing sequence)
        row['shares'] = (start_capital * half_kelly) // row['Close'] ## you need to divide cluster stats from target with USO - check clusters stats df for % or decimals 
        row[f'target_{k_names[k]}'] = round((1 - cluster_stats.loc["median" , f"open_low_{k_names[k]}"]/100) * row['Open'], 2) 
        row[f'k{k_names[k]}_true'] = (row[f'target_{k_names[k]}'] >= row['Low']) 
        row[f'k{k_names[k]}_profit'] = (row[f'k{k_names[k]}_true'] * (row['Open'] - row[f'target_{k_names[k]}']))* row['shares']
        row[f'k{k_names[k]}_loss'] = round(((row['Open'] - row['Close']) * row['shares']),4)
        row[f'k{k_names[k]}_pnl'] = np.where(row[f'k{k_names[k]}_true'] == True, row[f'k{k_names[k]}_profit'], row[f'k{k_names[k]}_loss'])
        del row[f'k{k_names[k]}_profit'], row[f'k{k_names[k]}_loss']
        
    
    row[f'k{k_names[0]}_k{k_names[1]}'] = np.where(row['predictions'] == 0, row[f'k{k_names[0]}_pnl'], row[f'k{k_names[1]}_pnl'])
    row['k0_k1_k2'] = np.where(row['predictions'] == no_trade_k, 0, row[f'k{k_names[0]}_k{k_names[1]}'] )
    row['tc'] = 2*(row['shares'] * tc) # new line for tc 
    row['net_pnl'] = np.where(row['k0_k1_k2'] != 0, row['k0_k1_k2'] - row['tc'], 0)
    row['eod_equity'] = start_capital + row['net_pnl']
    row['daily_ret'] = row['eod_equity'] / start_capital - 1
    row['half_kelly'] = half_kelly
    
    start_capital += row['net_pnl']
    df = pd.concat([df, row.to_frame().transpose()], axis= 0)

No kelly critetion:  2023-06-15 00:00:00
No kelly critetion:  2023-06-16 00:00:00
No kelly critetion:  2023-06-20 00:00:00
No kelly critetion:  2023-06-21 00:00:00
No kelly critetion:  2023-06-22 00:00:00
No kelly critetion:  2023-06-23 00:00:00
No kelly critetion:  2023-06-26 00:00:00
No kelly critetion:  2023-06-27 00:00:00
No kelly critetion:  2023-06-28 00:00:00
No kelly critetion:  2023-06-29 00:00:00
No kelly critetion:  2023-06-30 00:00:00
No kelly critetion:  2023-07-03 00:00:00
No kelly critetion:  2023-07-05 00:00:00
No kelly critetion:  2023-07-06 00:00:00
No kelly critetion:  2023-07-07 00:00:00
No kelly critetion:  2023-07-10 00:00:00
No kelly critetion:  2023-07-11 00:00:00
No kelly critetion:  2023-07-12 00:00:00
No kelly critetion:  2023-07-13 00:00:00
No kelly critetion:  2023-07-14 00:00:00
No kelly critetion:  2023-07-17 00:00:00
No kelly critetion:  2023-07-18 00:00:00
No kelly critetion:  2023-07-19 00:00:00
No kelly critetion:  2023-07-20 00:00:00
No kelly critetion:  2023-07-21 00:00:00
No kelly critetion:  2023-07-24 00:00:00
No kelly critetion:  2023-07-25 00:00:00
No kelly critetion:  2023-07-26 00:00:00
No kelly critetion:  2023-07-27 00:00:00
No kelly critetion:  2023-07-28 00:00:00
No kelly critetion:  2023-07-31 00:00:00
No kelly critetion:  2023-08-01 00:00:00
No kelly critetion:  2023-08-02 00:00:00
No kelly critetion:  2023-08-03 00:00:00
No kelly critetion:  2023-08-04 00:00:00
No kelly critetion:  2023-08-07 00:00:00
No kelly critetion:  2023-08-08 00:00:00
No kelly critetion:  2023-08-09 00:00:00
No kelly critetion:  2023-08-10 00:00:00
No kelly critetion:  2023-08-11 00:00:00
No kelly critetion:  2023-08-14 00:00:00
No kelly critetion:  2023-08-15 00:00:00
No kelly critetion:  2023-08-16 00:00:00
No kelly critetion:  2023-08-17 00:00:00
No kelly critetion:  2023-08-18 00:00:00
No kelly critetion:  2023-08-21 00:00:00
No kelly critetion:  2023-08-22 00:00:00
No kelly critetion:  2023-08-23 00:00:00
No kelly critetion:  2023-08-24 00:00:00
No kelly critetion:  2023-08-25 00:00:00
No kelly critetion:  2023-08-28 00:00:00
No kelly critetion:  2023-08-29 00:00:00
No kelly critetion:  2023-08-30 00:00:00
No kelly critetion:  2023-08-31 00:00:00
No kelly critetion:  2023-09-01 00:00:00
No kelly critetion:  2023-09-05 00:00:00
No kelly critetion:  2023-09-06 00:00:00
No kelly critetion:  2023-09-07 00:00:00
No kelly critetion:  2023-09-08 00:00:00
No kelly critetion:  2023-09-11 00:00:00
No kelly critetion:  2023-09-12 00:00:00
No kelly critetion:  2023-09-13 00:00:00
No kelly critetion:  2023-09-14 00:00:00
No kelly critetion:  2023-09-15 00:00:00
No kelly critetion:  2023-09-18 00:00:00
No kelly critetion:  2023-09-19 00:00:00
No kelly critetion:  2023-09-20 00:00:00
No kelly critetion:  2023-09-21 00:00:00
No kelly critetion:  2023-09-22 00:00:00
No kelly critetion:  2023-09-25 00:00:00
No kelly critetion:  2023-09-26 00:00:00
No kelly critetion:  2023-09-27 00:00:00
No kelly critetion:  2023-09-28 00:00:00
No kelly critetion:  2023-09-29 00:00:00
No kelly critetion:  2023-10-02 00:00:00
No kelly critetion:  2023-10-03 00:00:00
No kelly critetion:  2023-10-04 00:00:00
No kelly critetion:  2023-10-05 00:00:00
No kelly critetion:  2023-10-06 00:00:00
No kelly critetion:  2023-10-09 00:00:00
No kelly critetion:  2023-10-10 00:00:00
No kelly critetion:  2023-10-11 00:00:00
No kelly critetion:  2023-10-12 00:00:00
No kelly critetion:  2023-10-13 00:00:00
No kelly critetion:  2023-10-16 00:00:00
No kelly critetion:  2023-10-17 00:00:00
No kelly critetion:  2023-10-18 00:00:00
No kelly critetion:  2023-10-19 00:00:00
No kelly critetion:  2023-10-20 00:00:00
No kelly critetion:  2023-10-23 00:00:00
No kelly critetion:  2023-10-24 00:00:00
No kelly critetion:  2023-10-25 00:00:00
No kelly critetion:  2023-10-26 00:00:00
No kelly critetion:  2023-10-27 00:00:00
No kelly critetion:  2023-10-30 00:00:00
No kelly critetion:  2023-10-31 00:00:00
No kelly critetion:  2023-11-01 00:00:00
No kelly critetion:  2023-11-02 00:00:00
No kelly critetion:  2023-11-03 00:00:00
No kelly critetion:  2023-11-06 00:00:00
No kelly critetion:  2023-11-07 00:00:00
No kelly critetion:  2023-11-08 00:00:00
No kelly critetion:  2023-11-09 00:00:00
No kelly critetion:  2023-11-10 00:00:00
No kelly critetion:  2023-11-13 00:00:00
No kelly critetion:  2023-11-14 00:00:00
No kelly critetion:  2023-11-15 00:00:00
No kelly critetion:  2023-11-16 00:00:00
No kelly critetion:  2023-11-17 00:00:00
No kelly critetion:  2023-11-20 00:00:00
No kelly critetion:  2023-11-21 00:00:00
No kelly critetion:  2023-11-22 00:00:00
No kelly critetion:  2023-11-24 00:00:00
No kelly critetion:  2023-11-27 00:00:00
No kelly critetion:  2023-11-28 00:00:00
No kelly critetion:  2023-11-29 00:00:00
No kelly critetion:  2023-11-30 00:00:00
No kelly critetion:  2023-12-01 00:00:00
No kelly critetion:  2023-12-04 00:00:00
No kelly critetion:  2023-12-05 00:00:00
No kelly critetion:  2023-12-06 00:00:00
No kelly critetion:  2023-12-07 00:00:00
No kelly critetion:  2023-12-08 00:00:00
No kelly critetion:  2023-12-11 00:00:00
No kelly critetion:  2023-12-12 00:00:00
No kelly critetion:  2023-12-13 00:00:00
No kelly critetion:  2023-12-14 00:00:00
No kelly critetion:  2023-12-15 00:00:00
No kelly critetion:  2023-12-18 00:00:00
No kelly critetion:  2023-12-19 00:00:00
No kelly critetion:  2023-12-20 00:00:00
No kelly critetion:  2023-12-21 00:00:00
No kelly critetion:  2023-12-22 00:00:00
No kelly critetion:  2023-12-26 00:00:00
No kelly critetion:  2023-12-27 00:00:00
No kelly critetion:  2023-12-28 00:00:00
No kelly critetion:  2023-12-29 00:00:00
No kelly critetion:  2024-01-02 00:00:00
No kelly critetion:  2024-01-03 00:00:00
No kelly critetion:  2024-01-04 00:00:00
No kelly critetion:  2024-01-05 00:00:00
No kelly critetion:  2024-01-08 00:00:00
No kelly critetion:  2024-01-09 00:00:00
No kelly critetion:  2024-01-10 00:00:00
No kelly critetion:  2024-01-11 00:00:00
No kelly critetion:  2024-01-12 00:00:00
No kelly critetion:  2024-01-16 00:00:00
No kelly critetion:  2024-01-17 00:00:00
No kelly critetion:  2024-01-18 00:00:00
No kelly critetion:  2024-01-19 00:00:00
No kelly critetion:  2024-01-22 00:00:00
No kelly critetion:  2024-01-23 00:00:00
No kelly critetion:  2024-01-24 00:00:00
No kelly critetion:  2024-01-25 00:00:00
No kelly critetion:  2024-01-26 00:00:00
No kelly critetion:  2024-01-29 00:00:00
No kelly critetion:  2024-01-30 00:00:00
No kelly critetion:  2024-01-31 00:00:00
No kelly critetion:  2024-02-01 00:00:00
No kelly critetion:  2024-02-02 00:00:00
No kelly critetion:  2024-02-05 00:00:00
No kelly critetion:  2024-02-06 00:00:00
No kelly critetion:  2024-02-07 00:00:00
No kelly critetion:  2024-02-08 00:00:00
No kelly critetion:  2024-02-09 00:00:00
No kelly critetion:  2024-02-12 00:00:00
No kelly critetion:  2024-02-13 00:00:00
No kelly critetion:  2024-02-14 00:00:00
No kelly critetion:  2024-02-15 00:00:00
No kelly critetion:  2024-02-16 00:00:00
No kelly critetion:  2024-02-20 00:00:00
No kelly critetion:  2024-02-21 00:00:00
No kelly critetion:  2024-02-22 00:00:00
No kelly critetion:  2024-02-23 00:00:00
No kelly critetion:  2024-02-26 00:00:00
No kelly critetion:  2024-02-27 00:00:00
No kelly critetion:  2024-02-28 00:00:00
No kelly critetion:  2024-02-29 00:00:00
No kelly critetion:  2024-03-01 00:00:00
No kelly critetion:  2024-03-04 00:00:00
No kelly critetion:  2024-03-05 00:00:00
No kelly critetion:  2024-03-06 00:00:00
No kelly critetion:  2024-03-07 00:00:00
No kelly critetion:  2024-03-08 00:00:00
No kelly critetion:  2024-03-11 00:00:00
No kelly critetion:  2024-03-12 00:00:00
No kelly critetion:  2024-03-13 00:00:00
No kelly critetion:  2024-03-14 00:00:00
No kelly critetion:  2024-03-15 00:00:00
No kelly critetion:  2024-03-18 00:00:00
No kelly critetion:  2024-03-19 00:00:00
No kelly critetion:  2024-03-20 00:00:00
No kelly critetion:  2024-03-21 00:00:00
No kelly critetion:  2024-03-22 00:00:00
No kelly critetion:  2024-03-25 00:00:00
No kelly critetion:  2024-03-26 00:00:00
No kelly critetion:  2024-03-27 00:00:00
No kelly critetion:  2024-03-28 00:00:00
No kelly critetion:  2024-04-01 00:00:00
No kelly critetion:  2024-04-02 00:00:00
No kelly critetion:  2024-04-03 00:00:00
No kelly critetion:  2024-04-04 00:00:00
No kelly critetion:  2024-04-05 00:00:00
No kelly critetion:  2024-04-08 00:00:00
No kelly critetion:  2024-04-09 00:00:00
No kelly critetion:  2024-04-10 00:00:00
No kelly critetion:  2024-04-11 00:00:00
No kelly critetion:  2024-04-12 00:00:00
No kelly critetion:  2024-04-15 00:00:00
No kelly critetion:  2024-04-16 00:00:00
No kelly critetion:  2024-04-17 00:00:00
No kelly critetion:  2024-04-18 00:00:00
No kelly critetion:  2024-04-19 00:00:00
No kelly critetion:  2024-04-22 00:00:00
No kelly critetion:  2024-04-23 00:00:00
No kelly critetion:  2024-04-24 00:00:00
No kelly critetion:  2024-04-25 00:00:00
No kelly critetion:  2024-04-26 00:00:00
No kelly critetion:  2024-04-29 00:00:00
No kelly critetion:  2024-04-30 00:00:00
No kelly critetion:  2024-05-01 00:00:00
No kelly critetion:  2024-05-02 00:00:00
No kelly critetion:  2024-05-03 00:00:00
No kelly critetion:  2024-05-06 00:00:00
No kelly critetion:  2024-05-07 00:00:00
No kelly critetion:  2024-05-08 00:00:00
No kelly critetion:  2024-05-09 00:00:00
No kelly critetion:  2024-05-10 00:00:00
No kelly critetion:  2024-05-13 00:00:00
No kelly critetion:  2024-05-14 00:00:00
No kelly critetion:  2024-05-15 00:00:00
No kelly critetion:  2024-05-16 00:00:00
No kelly critetion:  2024-05-17 00:00:00
No kelly critetion:  2024-05-20 00:00:00
No kelly critetion:  2024-05-21 00:00:00
No kelly critetion:  2024-05-22 00:00:00
No kelly critetion:  2024-05-23 00:00:00
No kelly critetion:  2024-05-24 00:00:00
No kelly critetion:  2024-05-28 00:00:00
No kelly critetion:  2024-05-29 00:00:00
No kelly critetion:  2024-05-30 00:00:00
No kelly critetion:  2024-05-31 00:00:00
No kelly critetion:  2024-06-03 00:00:00
No kelly critetion:  2024-06-04 00:00:00
No kelly critetion:  2024-06-05 00:00:00
No kelly critetion:  2024-06-06 00:00:00
No kelly critetion:  2024-06-07 00:00:00
No kelly critetion:  2024-06-10 00:00:00
No kelly critetion:  2024-06-11 00:00:00
No kelly critetion:  2024-06-12 00:00:00
No kelly critetion:  2024-06-13 00:00:00
No kelly critetion:  2024-06-14 00:00:00
No kelly critetion:  2024-06-17 00:00:00
No kelly critetion:  2024-06-18 00:00:00
No kelly critetion:  2024-06-20 00:00:00
No kelly critetion:  2024-06-21 00:00:00
No kelly critetion:  2024-06-24 00:00:00
No kelly critetion:  2024-06-25 00:00:00
No kelly critetion:  2024-06-26 00:00:00
No kelly critetion:  2024-06-27 00:00:00
No kelly critetion:  2024-06-28 00:00:00
No kelly critetion:  2024-07-01 00:00:00
No kelly critetion:  2024-07-02 00:00:00
No kelly critetion:  2024-07-03 00:00:00
No kelly critetion:  2024-07-05 00:00:00
No kelly critetion:  2024-07-08 00:00:00
No kelly critetion:  2024-07-09 00:00:00
No kelly critetion:  2024-07-10 00:00:00
No kelly critetion:  2024-07-11 00:00:00
No kelly critetion:  2024-07-12 00:00:00
No kelly critetion:  2024-07-15 00:00:00
No kelly critetion:  2024-07-16 00:00:00
No kelly critetion:  2024-07-17 00:00:00
No kelly critetion:  2024-07-18 00:00:00
No kelly critetion:  2024-07-19 00:00:00
No kelly critetion:  2024-07-22 00:00:00
No kelly critetion:  2024-07-23 00:00:00
No kelly critetion:  2024-07-24 00:00:00
No kelly critetion:  2024-07-25 00:00:00
No kelly critetion:  2024-07-26 00:00:00
No kelly critetion:  2024-07-29 00:00:00
No kelly critetion:  2024-07-30 00:00:00
No kelly critetion:  2024-07-31 00:00:00
No kelly critetion:  2024-08-01 00:00:00
No kelly critetion:  2024-08-02 00:00:00
No kelly critetion:  2024-08-05 00:00:00
No kelly critetion:  2024-08-06 00:00:00
No kelly critetion:  2024-08-07 00:00:00
No kelly critetion:  2024-08-08 00:00:00
No kelly critetion:  2024-08-09 00:00:00
No kelly critetion:  2024-08-12 00:00:00
No kelly critetion:  2024-08-13 00:00:00
No kelly critetion:  2024-08-14 00:00:00
No kelly critetion:  2024-08-15 00:00:00
No kelly critetion:  2024-08-16 00:00:00
No kelly critetion:  2024-08-19 00:00:00
No kelly critetion:  2024-08-20 00:00:00
No kelly critetion:  2024-08-21 00:00:00
No kelly critetion:  2024-08-22 00:00:00
No kelly critetion:  2024-08-23 00:00:00
No kelly critetion:  2024-08-26 00:00:00
No kelly critetion:  2024-08-27 00:00:00
No kelly critetion:  2024-08-28 00:00:00
No kelly critetion:  2024-08-29 00:00:00
No kelly critetion:  2024-08-30 00:00:00
No kelly critetion:  2024-09-03 00:00:00
No kelly critetion:  2024-09-04 00:00:00
No kelly critetion:  2024-09-05 00:00:00
No kelly critetion:  2024-09-06 00:00:00
No kelly critetion:  2024-09-09 00:00:00
No kelly critetion:  2024-09-10 00:00:00
No kelly critetion:  2024-09-11 00:00:00
No kelly critetion:  2024-09-12 00:00:00
No kelly critetion:  2024-09-13 00:00:00
No kelly critetion:  2024-09-16 00:00:00
No kelly critetion:  2024-09-17 00:00:00
No kelly critetion:  2024-09-18 00:00:00
No kelly critetion:  2024-09-19 00:00:00
No kelly critetion:  2024-09-20 00:00:00
No kelly critetion:  2024-09-23 00:00:00
No kelly critetion:  2024-09-24 00:00:00
No kelly critetion:  2024-09-25 00:00:00
No kelly critetion:  2024-09-26 00:00:00
No kelly critetion:  2024-09-27 00:00:00
No kelly critetion:  2024-09-30 00:00:00
No kelly critetion:  2024-10-01 00:00:00
No kelly critetion:  2024-10-02 00:00:00
No kelly critetion:  2024-10-03 00:00:00
No kelly critetion:  2024-10-04 00:00:00
No kelly critetion:  2024-10-07 00:00:00
No kelly critetion:  2024-10-08 00:00:00
No kelly critetion:  2024-10-09 00:00:00
No kelly critetion:  2024-10-10 00:00:00
No kelly critetion:  2024-10-11 00:00:00
No kelly critetion:  2024-10-14 00:00:00
No kelly critetion:  2024-10-15 00:00:00
No kelly critetion:  2024-10-16 00:00:00
No kelly critetion:  2024-10-17 00:00:00
No kelly critetion:  2024-10-18 00:00:00
No kelly critetion:  2024-10-21 00:00:00
No kelly critetion:  2024-10-22 00:00:00
No kelly critetion:  2024-10-23 00:00:00
No kelly critetion:  2024-10-24 00:00:00
No kelly critetion:  2024-10-25 00:00:00
No kelly critetion:  2024-10-28 00:00:00
No kelly critetion:  2024-10-29 00:00:00
No kelly critetion:  2024-10-30 00:00:00
No kelly critetion:  2024-10-31 00:00:00
No kelly critetion:  2024-11-01 00:00:00
No kelly critetion:  2024-11-04 00:00:00
No kelly critetion:  2024-11-05 00:00:00
No kelly critetion:  2024-11-06 00:00:00
No kelly critetion:  2024-11-07 00:00:00
No kelly critetion:  2024-11-08 00:00:00
No kelly critetion:  2024-11-11 00:00:00
No kelly critetion:  2024-11-12 00:00:00
No kelly critetion:  2024-11-13 00:00:00
No kelly critetion:  2024-11-14 00:00:00
No kelly critetion:  2024-11-15 00:00:00
No kelly critetion:  2024-11-18 00:00:00
No kelly critetion:  2024-11-19 00:00:00
No kelly critetion:  2024-11-20 00:00:00
No kelly critetion:  2024-11-21 00:00:00
No kelly critetion:  2024-11-22 00:00:00
No kelly critetion:  2024-11-25 00:00:00
No kelly critetion:  2024-11-26 00:00:00
No kelly critetion:  2024-11-27 00:00:00
No kelly critetion:  2024-11-29 00:00:00
No kelly critetion:  2024-12-02 00:00:00
No kelly critetion:  2024-12-03 00:00:00
No kelly critetion:  2024-12-04 00:00:00
No kelly critetion:  2024-12-05 00:00:00
No kelly critetion:  2024-12-06 00:00:00
No kelly critetion:  2024-12-09 00:00:00
No kelly critetion:  2024-12-10 00:00:00
No kelly critetion:  2024-12-11 00:00:00
No kelly critetion:  2024-12-12 00:00:00
No kelly critetion:  2024-12-13 00:00:00
No kelly critetion:  2024-12-16 00:00:00
No kelly critetion:  2024-12-17 00:00:00
No kelly critetion:  2024-12-18 00:00:00
No kelly critetion:  2024-12-19 00:00:00
No kelly critetion:  2024-12-20 00:00:00
No kelly critetion:  2024-12-23 00:00:00
No kelly critetion:  2024-12-24 00:00:00
No kelly critetion:  2024-12-26 00:00:00
No kelly critetion:  2024-12-27 00:00:00
No kelly critetion:  2024-12-30 00:00:00
No kelly critetion:  2024-12-31 00:00:00
No kelly critetion:  2025-01-02 00:00:00
No kelly critetion:  2025-01-03 00:00:00
No kelly critetion:  2025-01-06 00:00:00
No kelly critetion:  2025-01-07 00:00:00
No kelly critetion:  2025-01-08 00:00:00
No kelly critetion:  2025-01-10 00:00:00
No kelly critetion:  2025-01-13 00:00:00
No kelly critetion:  2025-01-14 00:00:00
No kelly critetion:  2025-01-15 00:00:00
No kelly critetion:  2025-01-16 00:00:00
No kelly critetion:  2025-01-17 00:00:00
No kelly critetion:  2025-01-21 00:00:00
No kelly critetion:  2025-01-22 00:00:00
No kelly critetion:  2025-01-23 00:00:00
No kelly critetion:  2025-01-24 00:00:00
No kelly critetion:  2025-01-27 00:00:00
No kelly critetion:  2025-01-28 00:00:00
No kelly critetion:  2025-01-29 00:00:00
No kelly critetion:  2025-01-30 00:00:00
No kelly critetion:  2025-01-31 00:00:00
No kelly critetion:  2025-02-03 00:00:00
No kelly critetion:  2025-02-04 00:00:00
No kelly critetion:  2025-02-05 00:00:00
No kelly critetion:  2025-02-06 00:00:00
No kelly critetion:  2025-02-07 00:00:00
No kelly critetion:  2025-02-10 00:00:00
No kelly critetion:  2025-02-11 00:00:00
No kelly critetion:  2025-02-12 00:00:00
No kelly critetion:  2025-02-13 00:00:00
No kelly critetion:  2025-02-14 00:00:00
No kelly critetion:  2025-02-18 00:00:00
No kelly critetion:  2025-02-19 00:00:00
No kelly critetion:  2025-02-20 00:00:00
No kelly critetion:  2025-02-21 00:00:00
No kelly critetion:  2025-02-24 00:00:00
No kelly critetion:  2025-02-25 00:00:00
No kelly critetion:  2025-02-26 00:00:00
No kelly critetion:  2025-02-27 00:00:00
No kelly critetion:  2025-02-28 00:00:00
No kelly critetion:  2025-03-03 00:00:00
No kelly critetion:  2025-03-04 00:00:00
No kelly critetion:  2025-03-05 00:00:00
No kelly critetion:  2025-03-06 00:00:00
No kelly critetion:  2025-03-07 00:00:00
No kelly critetion:  2025-03-10 00:00:00
No kelly critetion:  2025-03-11 00:00:00
No kelly critetion:  2025-03-12 00:00:00
No kelly critetion:  2025-03-13 00:00:00
No kelly critetion:  2025-03-14 00:00:00
No kelly critetion:  2025-03-17 00:00:00
No kelly critetion:  2025-03-18 00:00:00
No kelly critetion:  2025-03-19 00:00:00
No kelly critetion:  2025-03-20 00:00:00
No kelly critetion:  2025-03-21 00:00:00
No kelly critetion:  2025-03-24 00:00:00
No kelly critetion:  2025-03-25 00:00:00
No kelly critetion:  2025-03-26 00:00:00
No kelly critetion:  2025-03-27 00:00:00
No kelly critetion:  2025-03-28 00:00:00
No kelly critetion:  2025-03-31 00:00:00
No kelly critetion:  2025-04-01 00:00:00
No kelly critetion:  2025-04-02 00:00:00
No kelly critetion:  2025-04-03 00:00:00
No kelly critetion:  2025-04-04 00:00:00
No kelly critetion:  2025-04-07 00:00:00
No kelly critetion:  2025-04-08 00:00:00
No kelly critetion:  2025-04-09 00:00:00
No kelly critetion:  2025-04-10 00:00:00
No kelly critetion:  2025-04-11 00:00:00
No kelly critetion:  2025-04-14 00:00:00
No kelly critetion:  2025-04-15 00:00:00
No kelly critetion:  2025-04-16 00:00:00
No kelly critetion:  2025-04-17 00:00:00
No kelly critetion:  2025-04-21 00:00:00
No kelly critetion:  2025-04-22 00:00:00
No kelly critetion:  2025-04-23 00:00:00

In [76]:
### FORMAT df - datatypes 
for col in list(df.columns):
    
    if ("true" or "last_day") in col:
        df[col] = df[col].astype("bool")
        
    elif ("labels" or "Volume" or "predictions") in col:
        df[col] = df[col].astype("int32")
    
    else:
        df[col] = df[col].astype("float64")
    
#del df2

df1 = df.copy()

df1['pnl_cumsum'] = df1['net_pnl'].cumsum()

In [77]:
#####################################################################
 # PERFORMANCE EVALUATION 
#####################################################################

#####   MAX DRAWDOWN
from calculateMaxDD import calculateMaxDD

cum_ret = np.cumprod(1+ df1['daily_ret']) - 1
maxDrawdown, maxDrawdownDuration, startDrawdownDay=calculateMaxDD(cum_ret.values)

#####   SHARPE RATIO
sharpe_ratio = round(np.sqrt(252) * np.mean(df1['daily_ret']) / np.std(df1['daily_ret']),2)

#####   AVG YEARLY RETURN AND STD
mean_ret = df1['daily_ret'].mean() * 252
std = df1['daily_ret'].std()*np.sqrt(252)

p_change = df1['Close'].pct_change().dropna() #/ df1['Close'].shift(1)
corr = np.corrcoef(p_change, df1['Close'][1:])

print(f"Correlation Price / Return: " , round(corr[1][0], 2))
print(f'Sharpe Ratio: {sharpe_ratio}')
print(f'Maximum Drawdown: {round(maxDrawdown,4)}')
print(f'Max Drawdown Duration: {maxDrawdownDuration} days' )
print(f'Start day Drawdown: {startDrawdownDay}')
print(f"Average Yearly Return: {round(mean_ret*100, 2)} %")

Correlation Price / Return:  0.02
Sharpe Ratio: -1.41
Maximum Drawdown: -0.2523
Max Drawdown Duration: 361.0 days
Start day Drawdown: 455
Average Yearly Return: -14.23 %